.TH "incrond" "8" "0.3.1" "Lukas Jelinek" "incron documentation"
.SH "NAME"
incrond \- inotify cron (incron) daemon

.SH "SYNOPSIS"
\fBincrond\fR
.SH "DESCRIPTION"
The inotify cron daemon (\fIincrond\fR) is a daemon which monitors filesystem events and executes commands defined in user tables. It's use is generally similar to \fIcron\fR(8).

\fIincrond\fR can be started from /etc/rc, /etc/rc.local and so on. It daemonizes itself (returns immediately) and doesn't need to be started with & and through \fInohup\fR(1). Running on foreground is currently not possible but it will be implemented in the future.

\fIincrond\fR searches /var/spool/incron for \fIincrontab\fR(5) files named after user accounts. If a table (incrontab) is changed \fIincrond\fR reacts immediately and reloads the table. Currently running subprocesses (commands) are not affected.

There are two files determining whether an user is allowed to use incron. These files have very simple syntax \- one user name per line. If /etc/incron.allow exists the user must be noted there to be allowed to use incron. Otherwise if /etc/incron.deny exists the user must not be noted there to use incron. If none of these files exists there is no other restriction whether anybody may use incron.

The daemon itself is currently not protected against looping. If a command executed due to an event causes the same event it leads to an infinite loop unless a flag mask containing IN_NO_LOOP is specified. Please beware of this and do not allow permission for use incron to unreliable users.
.SH "SEE ALSO"
incrontab(1), incrontab(5)
.SH "BUGS"
incrond is currently not resistent against looping.
.SH "AUTHOR"
Lukas Jelinek <lukas@aiken.cz>
.SH "COPYING"
This program is free software. It can be used, redistributed and/or modified under the terms of the GNU General Public License, version 2.
