.TH "incrontab" "1" "0.5.1" "Lukas Jelinek" "incron documentation"
.SH "NAME"
incrontab \- table manipulator for inotify cron (incron)
.SH "SYNOPSIS"
\fBincrontab\fR [\fB\-u\fR \fIuser\fR] [\fB\-f\fR \fIconfig\fR] \fIfile\fR

\fBincrontab\fR [\fB\-u\fR \fIuser\fR] [\fB\-f\fR \fIconfig\fR] [\fB\-l\fR | \fB\-r\fR | \fB\-e\fR | \fB\-t\fR | \fB\-d\fR]
.SH "DESCRIPTION"
incrontab is a table manipulator for the inotify cron (incron) system. It creates, removes, modifies and lists user tables (\fIincrontab\fR(5)).

Each user (including system users even they haven't home directories) has an incron table which can't be manipulated directly (only root can effectively change these tables and is NOT recommended to do so).

All informational messages of this program are printed to the standard error output (stderr).

If \fI/etc/incron.allow\fR exists only users listed here may use incron. Otherwise if \fI/etc/incron.deny\fR exists only users NOT listed here may use incron. If none of these files exists everyone is allowed to use incron. (\fBImportant note:\fR This behavior is insecure and will be probably changed to be compatible with the style used by ISC Cron.) Location of this files can be changed in the configuration.

The first form of this command imports a file, validates it and stores to the table. "\-" can be used for loading from the standard input.



\fB\-u\fR (or \fB\-\-user\fR) option overrides the current (real) user to the given one. This option is intended for manipulation with system users' tables (such as apache, postfix, daemon etc.). It can be used only if the current user has root's effective rights.

\fB\-l\fR (or \fB\-\-list\fR) option causes the current table is printed to the standard output.

\fB\-r\fR (or \fB\-\-remove\fR) option causes the current table (if any) is permanently remove without any warning or confirmation. Use with caution!

\fB\-e\fR (or \fB\-\-edit\fR) option causes executing an editor for editting the user table (see below for the information about editor selection). You can edit your incron table now. If the table is changed it stores the modified version.

\fB\-t\fR (or \fB\-\-types\fR) option causes the list of supported event types (delimited by commas) is printed to the standard output. This feature is intended for front\-end applications to find out which event types was compiled in.

\fB\-f <FILE>\fR (or \fB\-\-config=<FILE>\fR) option specifies another location for the configuration file (/etc/incron.conf is used by default). This feature requires root privileges.

There is a few complex algorithm how to determine which editor will be user for editting. If any of the following rule succeeds the appropriate editor is used:

1. EDITOR environment variable

2. VISUAL environment variable

3. configuration value

4. etc/alternatives/editor

5. hard\-wired editor (\fIvim\fR by default)

It's not recommended to use graphical editors (such as gVim, KEdit etc.) due to possible problems with connecting to the X server.
.SH "SEE ALSO"
incrond(8), incrontab(5)
.SH "AUTHOR"
Lukas Jelinek <lukas@aiken.cz>
.SH "COPYING"
This program is free software. It can be used, redistributed and/or modified under the terms of the GNU General Public License, version 2.
