.TH "AppArgOption_t" 3 "Sat Apr 7 2012" "Version 0.5.10" "incron" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AppArgOption_t \- 
.PP
Argument option type'\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <appargs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAppArgType_t\fP \fBtype\fP"
.br
.RI "\fIargument type \fP"
.ti -1c
.RI "bool \fBmand\fP"
.br
.RI "\fImandatory yes/no \fP"
.ti -1c
.RI "bool \fBfound\fP"
.br
.RI "\fIfound in argument vector \fP"
.ti -1c
.RI "std::string \fBval\fP"
.br
.RI "\fIvalue \fP"
.ti -1c
.RI "bool \fBhasVal\fP"
.br
.RI "\fIvalue is set \fP"
.in -1c
.SH "Detailed Description"
.PP 
Argument option type'\&. 
.SH "Member Data Documentation"
.PP 
.SS "bool \fBAppArgOption_t::found\fP"
.PP
found in argument vector 
.SS "bool \fBAppArgOption_t::hasVal\fP"
.PP
value is set 
.SS "bool \fBAppArgOption_t::mand\fP"
.PP
mandatory yes/no 
.SS "\fBAppArgType_t\fP \fBAppArgOption_t::type\fP"
.PP
argument type 
.SS "std::string \fBAppArgOption_t::val\fP"
.PP
value 

.SH "Author"
.PP 
Generated automatically by Doxygen for incron from the source code'\&.
