.TH "appinst.cpp" 3 "Sat Apr 7 2012" "Version 0.5.10" "incron" \" -*- nroff -*-
.ad l
.nh
.SH NAME
appinst.cpp \- 
.PP
Application instance class implementation'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <fcntl\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include 'appinst\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBAPPLOCK_PERM\fP   (S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH)"
.br
.RI "\fILockfile permissions (currently 0644) \fP"
.in -1c
.SH "Detailed Description"
.PP 
Application instance class implementation'\&. 

Copyright (C) 2007, 2008, 2012 Lukas Jelinek, <lukas@aiken.cz>
.PP
This program is free software; you can redistribute it and/or modify it under the terms of one of the following licenses:
.PP
.PD 0
.IP "\(bu" 2
1'\&. X11-style license (see LICENSE-X11) 
.IP "\(bu" 2
2'\&. GNU Lesser General Public License, version 2'\&.1 (see LICENSE-LGPL) 
.IP "\(bu" 2
3'\&. GNU General Public License, version 2 (see LICENSE-GPL)
.PP
If you want to help with choosing the best license for you, please visit http://www.gnu.org/licenses/license-list.html.
.PP
Credits: Christian Ruppert (new include to build with GCC 4'\&.4+) 
.SH "Define Documentation"
.PP 
.SS "#define APPLOCK_PERM   (S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH)"
.PP
Lockfile permissions (currently 0644) 
.SH "Author"
.PP 
Generated automatically by Doxygen for incron from the source code'\&.
