.TH "AppInstException" 3 "Sat Apr 7 2012" "Version 0.5.10" "incron" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AppInstException \- 
.PP
Exception class'\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <appinst\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAppInstException\fP (int iErr)"
.br
.RI "\fIConstructor'\&. \fP"
.ti -1c
.RI "int \fBGetErrorNumber\fP () const "
.br
.RI "\fIReturns the error number'\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Exception class'\&. 

This class provides information about occurred errors'\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AppInstException::AppInstException (intiErr)\fC [inline]\fP"
.PP
Constructor'\&. \fBParameters:\fP
.RS 4
\fIiErr\fP error number 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "int AppInstException::GetErrorNumber () const\fC [inline]\fP"
.PP
Returns the error number'\&. \fBReturns:\fP
.RS 4
error number 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for incron from the source code'\&.
