.TH "incrontab.h" 3 "Sat Apr 7 2012" "Version 0.5.10" "incron" \" -*- nroff -*-
.ad l
.nh
.SH NAME
incrontab.h \- 
.PP
inotify cron table manipulator classes header  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <deque>\fP
.br
\fC#include 'strtok\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIncronTabEntry\fP"
.br
.RI "\fIIncron table entry class'\&. \fP"
.ti -1c
.RI "class \fBIncronTab\fP"
.br
.RI "\fIIncron table class'\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
inotify cron table manipulator classes header 

inotify cron system
.PP
Copyright (C) 2006, 2007, 2008 Lukas Jelinek, <lukas@aiken.cz>
.PP
This program is free software; you can use it, redistribute it and/or modify it under the terms of the GNU General Public License, version 2 (see LICENSE-GPL)'\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for incron from the source code'\&.
