.TH "incrontab.cpp" 3 "Sat Apr 7 2012" "Version 0.5.10" "incron" \" -*- nroff -*-
.ad l
.nh
.SH NAME
incrontab.cpp \- 
.PP
inotify cron table manipulator classes implementation  

.SH SYNOPSIS
.br
.PP
\fC#include <sstream>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include 'inotify-cxx\&.h'\fP
.br
\fC#include 'incrontab\&.h'\fP
.br
\fC#include 'incroncfg\&.h'\fP
.br

.SH "Detailed Description"
.PP 
inotify cron table manipulator classes implementation 

inotify cron system
.PP
Copyright (C) 2006, 2007, 2008, 2012 Lukas Jelinek, <lukas@aiken.cz>
.PP
This program is free software; you can use it, redistribute it and/or modify it under the terms of the GNU General Public License, version 2 (see LICENSE-GPL)'\&.
.PP
Credits: Christian Ruppert (new include to build with GCC 4'\&.4+) 
.SH "Author"
.PP 
Generated automatically by Doxygen for incron from the source code'\&.
