.TH "incroncfg.h" 3 "Sat Apr 7 2012" "Version 0.5.10" "incron" \" -*- nroff -*-
.ad l
.nh
.SH NAME
incroncfg.h \- 
.PP
inotify cron configuration header  

.SH SYNOPSIS
.br
.PP
\fC#include <cstring>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIncronCfg\fP"
.br
.RI "\fIConfiguration class'\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
inotify cron configuration header 

incron configuration
.PP
Copyright (C) 2007, 2008 Lukas Jelinek, <lukas@aiken.cz>
.PP
This program is free software; you can use it, redistribute it and/or modify it under the terms of the GNU General Public License, version 2 (see LICENSE-GPL)'\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for incron from the source code'\&.
