.TH "incron.h" 3 "Sat Apr 7 2012" "Version 0.5.10" "incron" \" -*- nroff -*-
.ad l
.nh
.SH NAME
incron.h \- 
.PP
inotify cron basic definition file  

.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBINCRON_NAME\fP   'incron'"
.br
.RI "\fICommon application name'\&. \fP"
.ti -1c
.RI "#define \fBINCROND_NAME\fP   'incrond'"
.br
.RI "\fIDaemon name'\&. \fP"
.ti -1c
.RI "#define \fBINCRONTAB_NAME\fP   'incrontab'"
.br
.RI "\fITable manipulator name'\&. \fP"
.ti -1c
.RI "#define \fBINCRON_VERSION\fP   '0\&.5\&.10'"
.br
.RI "\fIApplication version (release) \fP"
.ti -1c
.RI "#define \fBINCRON_BUG_ADDRESS\fP   '<bugs@aiken\&.cz>'"
.br
.RI "\fIAddress for sending bugs'\&. \fP"
.ti -1c
.RI "#define \fBINCRON_CONFIG\fP   '/etc/incron\&.conf'"
.br
.RI "\fIDefault configuration file'\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
inotify cron basic definition file 

inotify cron system
.PP
Copyright (C) 2006, 2007, 2008, 2009 Lukas Jelinek, <lukas@aiken.cz>
.PP
This program is free software; you can use it, redistribute it and/or modify it under the terms of the GNU General Public License, version 2 (see LICENSE-GPL)'\&. 
.SH "Define Documentation"
.PP 
.SS "#define INCRON_BUG_ADDRESS   '<bugs@aiken\&.cz>'"
.PP
Address for sending bugs'\&. 
.SS "#define INCRON_CONFIG   '/etc/incron\&.conf'"
.PP
Default configuration file'\&. 
.SS "#define INCRON_NAME   'incron'"
.PP
Common application name'\&. 
.SS "#define INCRON_VERSION   '0\&.5\&.10'"
.PP
Application version (release) 
.SS "#define INCROND_NAME   'incrond'"
.PP
Daemon name'\&. 
.SS "#define INCRONTAB_NAME   'incrontab'"
.PP
Table manipulator name'\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for incron from the source code'\&.
