.TH "ProcData_t" 3 "Sat Apr 7 2012" "Version 0.5.10" "incron" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProcData_t \- 
.PP
Child process data'\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <usertable\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBproc_done_cb\fP \fBonDone\fP"
.br
.RI "\fIfunction called after process finishes \fP"
.ti -1c
.RI "\fBInotifyWatch\fP * \fBpWatch\fP"
.br
.RI "\fIrelated watch \fP"
.in -1c
.SH "Detailed Description"
.PP 
Child process data'\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBproc_done_cb\fP \fBProcData_t::onDone\fP"
.PP
function called after process finishes 
.SS "\fBInotifyWatch\fP* \fBProcData_t::pWatch\fP"
.PP
related watch 

.SH "Author"
.PP 
Generated automatically by Doxygen for incron from the source code'\&.
